default: &default
  adapter: postgresql
  port: 5432
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: my_event_development

test:
  <<: *default
  database: my_event_test
